#!/usr/bin/env python
from __future__ import print_function
import roslib
import sys
import rospy
import numpy as np
import datetime
import time
from geometry_msgs.msg import PoseArray
from geometry_msgs.msg import Pose
from dse_msgs.msg import PoseMarkers
from std_msgs.msg import Float64MultiArray
from std_msgs.msg import MultiArrayLayout
from std_msgs.msg import MultiArrayDimension
from dse_msgs.msg import InfFilterResults
from visualization_msgs.msg import Marker
from scipy.spatial.transform import Rotation as R
from gazebo_msgs.msg import LinkStates

import dse_lib
import dse_constants

roslib.load_manifest('dse_simulation')

class information_filter:

    # Define initial/setup values
    def __init__(self, dim_state):
        self.camera_pose_sub = rospy.Subscriber("/dse/pose_markers", PoseMarkers, self.measurement_callback)
        self.link_states_sub = rospy.Subscriber("/gazebo/link_states", LinkStates, self.true_callback)
        self.inf_results_sub = rospy.Subscriber("/dse/inf/results", InfFilterResults, self.results_callback)
        self.meas_vis_pub = rospy.Publisher("/dse/vis/measurement", PoseArray, queue_size=10)
        self.true_vis_pub = rospy.Publisher("/dse/vis/true", PoseArray, queue_size=10)
        self.est_vis_pub = rospy.Publisher("/dse/vis/estimates", PoseArray, queue_size=10)

        self.dim_state = dim_state
        if self.dim_state == 6:
            self.dim_obs = 3
        elif self.dim_state == 12:
            self.dim_obs = 6
        else:
            rospy.signal_shutdown('invalid state dimension passed in')

        # Define static variables
        self.dt = 0.1
        self.t_last = rospy.get_time()
        self.ref_obj_state = None

    # Create pose_array for measurement data
    def measurement_callback(self, data):
        data.pose_array.header.frame_id = 'odom'
        self.meas_vis_pub.publish(data.pose_array)

    # Create pose_array for the information results
    def true_callback(self, data):
        n = len(data.name)
        for i in range(n):
            if data.name[i] == dse_constants.GAZEBO_REFERENCE_OBJECT_NAME:
                self.ref_obj_state = dse_lib.state_from_pose_3D(data.pose[i])
                break

    # Create pose_array for the information results
    def results_callback(self, data):
        inf_id_list = np.array(data.ids)
        inf_Y = dse_lib.multi_array_2d_output(data.inf_matrix)
        inf_y = dse_lib.multi_array_2d_output(data.inf_vector)
        inf_x = np.linalg.inv(inf_Y).dot(inf_y)
        inf_P = np.linalg.inv(inf_Y)

        poses = PoseArray()
        poses.header.stamp = rospy.Time.now()
        poses.header.frame_id = 'odom'
        if self.ref_obj_state is not None:
            for i in range(len(inf_id_list)):

                i_low = self.dim_state * i
                i_high = i_low + self.dim_obs
                agent_i_state = inf_x[i_low:i_high]

                if self.dim_obs == 3:
                    estimation = dse_lib.observe_agent2_from_agent1_3D(self.ref_obj_state, agent_i_state)
                    poses.poses.append(dse_lib.pose_from_state_3D(estimation))
                else:
                    estimation = dse_lib.observe_agent2_from_agent1(self.ref_obj_state, agent_i_state)
                    poses.poses.append(dse_lib.pose_from_state(estimation))

        self.est_vis_pub.publish(poses)


def main(args):
    rospy.init_node('dse_gazebo_visualization_node', anonymous=True)
    il = information_filter(6)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")


if __name__ == '__main__':
    main(sys.argv)
