#!/usr/bin/env python
from __future__ import print_function
import roslib
import sys
import rospy
import numpy as np
import datetime
import time
from geometry_msgs.msg import PoseArray
from geometry_msgs.msg import Pose
from dse_msgs.msg import PoseMarkers
from std_msgs.msg import Float64MultiArray
from std_msgs.msg import MultiArrayLayout
from std_msgs.msg import MultiArrayDimension
from dse_msgs.msg import InfFilterResults
from visualization_msgs.msg import Marker
from scipy.spatial.transform import Rotation as R

from dse_lib import *

roslib.load_manifest('dse_simulation')

class information_filter:

    # Define initial/setup values
    def __init__(self, dim_state):
        self.pose_sub = rospy.Subscriber("/dse/pose_markers", PoseMarkers, self.measurement_callback)
        self.true_sub = rospy.Subscriber("/dse/pose_true", PoseMarkers, self.true_callback)
        self.results_sub = rospy.Subscriber("/dse/inf/results", InfFilterResults, self.results_callback)
        self.meas_vis_pub = rospy.Publisher("/dse/vis/measurement", PoseArray, queue_size=10)
        self.true_vis_pub = rospy.Publisher("/dse/vis/true", PoseArray, queue_size=10)
        self.est_vis_pub = rospy.Publisher("/dse/vis/estimates", PoseArray, queue_size=10)

        self.dim_state = dim_state
        if self.dim_state == 6:
            self.dim_obs = 3
        elif self.dim_state == 12:
            self.dim_obs = 6
        else:
            rospy.signal_shutdown('invalid state dimension passed in')

        # Define static variables
        self.dt = 0.1
        self.t_last = rospy.get_time()
        self.euler_order = 'zyx'

    # Create pose_array for measurement data
    def measurement_callback(self, data):
        data.pose_array.header.frame_id = 'odom'
        self.meas_vis_pub.publish(data.pose_array)

    # Create pose_array for the information results
    def true_callback(self, data):
        data.pose_array.header.frame_id = 'odom'
        self.true_vis_pub.publish(data.pose_array)

    # Create pose_array for the information results
    def results_callback(self, data):
        inf_id_list = np.array(data.ids)
        inf_Y = multi_array_2d_output(data.inf_matrix)
        inf_y = multi_array_2d_output(data.inf_vector)
        inf_x = np.linalg.inv(inf_Y).dot(inf_y)
        inf_P = np.linalg.inv(inf_Y)

        poses = PoseArray()
        poses.header.stamp = rospy.Time.now()
        poses.header.frame_id = 'odom'
        for i in range(len(inf_id_list)):
            pose = Pose()
            i_low = self.dim_state * i
            i_high = i_low + self.dim_obs

            if self.dim_obs == 3:
                self.euler_order = 'z'
                pose.position.x = inf_x[i_low]
                pose.position.y = inf_x[i_low + 1]
                pose.position.z = 0

                r = R.from_euler(self.euler_order, inf_x[i_low + 2, 0])
                quat = r.as_quat()
            else:
                pose.position.x = inf_x[i_low]
                pose.position.y = inf_x[i_low + 1]
                pose.position.z = inf_x[i_low + 2]

                r = R.from_euler(self.euler_order, inf_x[i_low + 3:i_low + 6, 0])
                quat = r.as_quat()

            pose.orientation.x = quat[0]
            pose.orientation.y = quat[1]
            pose.orientation.z = quat[2]
            pose.orientation.w = quat[3]
            poses.poses.append(pose)
        self.est_vis_pub.publish(poses)


def main(args):
    rospy.init_node('dse_visualization_node', anonymous=True)
    il = information_filter(6)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")


if __name__ == '__main__':
    main(sys.argv)
